import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nabvar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    apple: '/icon.png',

  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <div className="grid min-h-screen w-full overflow-hidden lg:grid-cols-[280px_1fr]">
          <Nabvar />
          <div className='min-h-screen w-full bg-gray-100'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
